---
title: "Outlier 'e' values"
author: "Meera"
date: "2023-04-19"
output: html_document
---

## Import R Libraries
```{r import}
library(rjags)
library(ggplot2)
library(MASS)
library(reshape2)
```

## Simulating Growth Curves

### Setting up variables
```{r variables}
ngeno = 100 # number of genotypes
nrep = 3 # number of replicates
# for reproducibility
seed = 13
set.seed(seed)
genotype = 1:ngeno
replicate = 1:nrep
```

### Simulating growth curves
```{r simulate}
R = diag(c(100,10,10))
df = 4
set.seed(seed)
sigma = solve(rWishart(n = 1, df = df, Sigma = R)[,,1])

print(sigma)
set.seed(seed)
mvmean = c(-0.5,0.5,20)
params = mvrnorm(ngeno, mvmean, sigma)
paramnames = c("b", "d", "e")
for (i in 1:3){
  print(paste("realized variance for",paramnames[i], ":", var(params[,i])))
}

colnames(params) = paramnames
data = as.data.frame(cbind(genotype, params))

alldata = c()
time = seq(0, 40, 5)

var_y = 0.001
sigma_y = diag(var_y, length(time))
for (i in 1:ngeno) {
  subdata = data[data$genotype == i,] # pick the genotype-specific b,d,e
  mu_arr = (subdata$d)/(1 + exp(subdata$b*(time-subdata$e))) # growth curve as mean
  set.seed(seed)
  y = mvrnorm(nrep, mu_arr, sigma_y) # n replicates
  for (j in 1:nrep) {
    alldata = rbind(alldata, cbind(rep(i, length(time)), rep(j, length(time)),time, y[j,]))
  }
}

alldata = as.data.frame(alldata)
colnames(alldata) = c("genotype", "rep", "time", "y")
alldata$rep = as.character(alldata$rep)

print("covariance matrix for growth curve parameters = ")
sigma
for (i in 1:3){
  print(paste("realized variance for",paramnames[i], ":", var(params[,i])))
}
```
### Run JAGS
```{r jags}
## ----JAGS prep-------------------------------------------
# alldata <- data.frame(fread('simgrowth.txt', header=TRUE, sep='\t'))

nrT = length(time)
for (geno in genotype) {
  ally = c()
  for (rep in replicate) {
    ally = c(ally, list(alldata[alldata$genotype == geno & alldata$rep == rep,]$y))
  }
  ally = do.call(rbind, ally)
  if(geno == 1) {
    res = array(ally, dim = c(nrep, length(time), 1))
  } else {
    res = array(c(res, ally), dim = c(nrep, length(time), dim(res)[3] + 1))
  }
}

dim(res) # should be n (rows) x nrT (columns) x ngeno (arrays)
# res # should be n (rows) x nrT (columns) x ngeno (arrays)

R = diag(c(100,100,100)) # uninformative scaled matrix
df = 4

jagsData <- list("Y"=res,"N"=ngeno,"nrT"=nrT,"time"=time, "nRep" = nrep, "R" = R, "df" = df)

model_string <- "model {
  # dimensions of Y matrix = nRep x nrT x N
  for (i in 1:N) { # loop over genotypes
    for (t in 1:nrT) { # loop over time points
      for (j in 1:nRep) {
        Y[j, t, i] ~ dnorm(params[i,2] / (1 + exp(params[i,1] * (time[t] - params[i,3]))), 1/pow(sd,2)) 
      }
    }
  }
  sd ~ dunif(0, 100)
  
  for (i in 1:N) { # loop over genotypes
    params[i, 1:3] ~ dmnorm(c(0,0,0), TAU[1:3, 1:3])
  }
  TAU ~ dwish(R, df)
  # output covariance matrix
  VCOV <- inverse(TAU)
  vars[1] <- VCOV[1,1]; vars[2] <- VCOV[2,2]; vars[3] <- VCOV[3,3]
  cov[1] <- VCOV[1,2]; cov[2] <- VCOV[1,3]; cov[3] <- VCOV[2,3]
}"

nadapt = 10000
nupdate = 75000
nimplement = 10000
# seed = seed + 1
parameters = c("params", "sd", "vars", "cov", "mu")
model <- jags.model(textConnection(model_string),
                    data=jagsData, n.chains=1, n.adapt = nadapt, inits = list(.RNG.name = "base::Wichmann-Hill",.RNG.seed = seed))

update(model, n.iter=nupdate)
samples <- coda.samples(model, variable.names=parameters, n.iter=nimplement)
s = as.data.frame(as.matrix(samples))
```
### Check for outliers
```{r outlier}
p = c("b", "d", "e")
i = 3 # for e
iterations = 9500:10000

param_index = grep("param", colnames(s))
param = colnames(s)[param_index]
index = param_index[grep(paste0(i,"\\]"),param)]
subset = as.data.frame(rowMeans(s[iterations,index]))

colnames(subset) = c("mean")
subset$iteration = iterations
subset$param = p[i]
graphdata = subset

graphdata$iteration = as.numeric(graphdata$iteration)

ggplot(graphdata) +
  geom_point(aes(iteration, mean)) + 
  facet_wrap(~param, scales = "free", nrow = 3) +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))

iterations = 9500:9800
start = ((i - 1) * ngeno) + 4
end = (i * ngeno) + 3
subset = as.data.frame(s[iterations,start:end])
subset$iteration = iterations
subset = melt(subset, id.vars = "iteration")
subset$param = p[i]
graphdata = subset

graphdata$genotype = gsub('\\D+','', graphdata$variable) # only keep numbers
graphdata$genotype = substr(graphdata$genotype,1,nchar(graphdata$genotype)-1) # remove last character "3"
graphdata$iteration = as.numeric(graphdata$iteration)

ggplot(graphdata, aes(iteration, value, col = genotype))+
  geom_point() + facet_wrap(~param, scales = "free_y", nrow = 3) +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))

sub_graph = graphdata[graphdata$value > 40 | graphdata$value < 0,]
sub_graph$iteration = as.numeric(sub_graph$iteration)


ggplot(sub_graph, aes(iteration, value, col = genotype))+
  geom_point() + facet_wrap(~param, scales = "free_y", nrow = 3) +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))

sub_graph$genotype = as.numeric(sub_graph$genotype)
bad_geno = unique(sub_graph$genotype)

total = nimplement; thin = c(10,10,10)
p = c("b", "d", "e")
print(ngeno)
for (i in 1:length(p)) {
  param_index = grep("param", colnames(s))
  param = colnames(s)[param_index]
  index = param_index[grep(paste0(i,"\\]"),param)]
  subset = as.data.frame(s[,index])
  save_cols = colnames(subset) 
  
  keep = seq(1, total,thin[i])
  subset = as.data.frame(subset[keep,])
  colnames(subset) = save_cols
  
  subset$iteration = 1:(total/thin[i])
  subset = melt(subset, id.vars = "iteration")
  subset$param = p[i]
  if(i == 1) {
    graphdata = subset
  }
  else {
    graphdata = rbind(graphdata, subset)
  }
}
graphdata$genotype = gsub('\\D+','', graphdata$variable) # only keep numbers
graphdata$genotype = substr(graphdata$genotype,1,nchar(graphdata$genotype)-1) # remove last character "3"
graphdata = graphdata[graphdata$genotype == as.character(bad_geno),] # keep only "bad" genotype
graphdata$iteration = as.numeric(graphdata$iteration)

ggplot(graphdata, aes(iteration, value)) +
  geom_point(color = "#18B79A") + facet_wrap(~param, scales = "free_y", nrow = 3) +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))

# plot growth curve
plot = ggplot() + geom_point(data = alldata[alldata$genotype %in% bad_geno,], aes(x = time, y = y, color = rep))
plot = plot + facet_wrap(~genotype) + ylim(c(0,1))
plot
```