---
title: "Incorporating GRM"
author: "Meera"
date: "2023-04-19"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import R Libraries
```{r import}
library(rjags)
library(MASS)
library(kinship2)
library(ggplot2)
```

## Simulating Growth Curves
### Simulating pedigree
```{r pedigree}
sample.ped = rbind(c(1,1,0,0,1), c(1,2,0,0,2), c(1,3,0,0,2), c(1,4,1,2,1), 
                   c(1,5,1,3,2), c(1,6,4,5,1), c(1,7,4,5,2), c(1,8,6,7,1))
colnames(sample.ped) = c("ped","id", "father", "mother", "sex")
sample.ped = as.data.frame(sample.ped)
# sample.ped
pedAll <- pedigree(id=sample.ped$id, dadid=sample.ped$father, 
                   momid=sample.ped$mother, sex = sample.ped$sex)
plot.pedigree(pedAll, cex = 0.5)
GRM = kinship(pedAll)
print(GRM)
```

### Setting up variables
```{r variables}
ngeno = dim(GRM)[1] # number of genotypes
nrep = 3 # number of replicates
# for reproducibility
seed = 13
set.seed(seed)
genotype = 1:ngeno
replicate = 1:nrep
```

### Simulating growth curves
$$
[b, d, e] \sim MVN(\ [-0.5,0.5,20]\ , \ \Sigma\ \otimes \text{GRM}) \\
\Sigma = \text{inverse Wishart } \bigg( S =  \begin{bmatrix}
    100 & & \\
    & 10 & \\
    & & 10
  \end{bmatrix}, \text{df} = 4 \bigg) \\
  y_{i,j} \sim MVN \bigg(\frac{d_i}{1 + exp(b_i(T - e_i))},  \begin{bmatrix}
    0.001 & & \\
    & \ddots & \\
    & & 0.001
  \end{bmatrix}\bigg)
$$
```{r simulation}
R = diag(c(100,10,10))
df = 4

set.seed(seed)
sigma = solve(rWishart(n = 1, df = df, Sigma = R)[,,1])
sigmaGRM = sigma %x% GRM
mean = c(-0.5,0.5,20)
mvmean = c(rep(mean[1],ngeno), rep(mean[2],ngeno), rep(mean[3],ngeno))
set.seed(seed)
params = mvrnorm(1, mvmean, sigmaGRM)

p = matrix(nrow = ngeno, ncol = 3)
for (i in 1:3) {
  p[,i] = params[(((i-1) * ngeno) + 1) : (i * ngeno)]
}

paramnames = c("b", "d", "e")
colnames(p) = paramnames
data = as.data.frame(cbind(genotype, p))

alldata = c()
time = seq(0, 40,5)
var_y = 0.001
sigma_y = diag(var_y, length(time)) 
for (i in 1:ngeno) {
  subdata = data[data$genotype == i,] # pick the genotype-specific b,d,e
  mu_arr = (subdata$d)/(1 + exp(subdata$b*(time-subdata$e))) # growth curve as mean
  set.seed(seed)
  y = mvrnorm(nrep, mu_arr, sigma_y) # n replicates
  for (j in 1:nrep) {
    alldata = rbind(alldata, cbind(rep(i, length(time)), rep(j, length(time)),time, y[j,]))
  }
}

alldata = as.data.frame(alldata)
colnames(alldata) = c("genotype", "rep", "time", "y")
alldata$rep = as.character(alldata$rep)
head(alldata)
```

### Summary of simulated growth curves
```{r summary}
print("covariance matrix (sigma) for growth curve parameters")
sigma
for (i in 1:3){
  print(paste("realized variance for",paramnames[i], ":", var(p[,i])))
}
```

### Visualise growth curves
```{r plot growth curve}
plot = ggplot() + geom_point(data = alldata, aes(x = time, y = y, color = rep))
plot = plot + facet_wrap(~genotype, nrow = 2)
plot
```

## JAGS model

### Reformat as JAGS input
```{r JAGS prep}
nrT = length(time)

for (geno in genotype) {
  ally = c()
  for (rep in replicate) {
    ally = c(ally, list(alldata[alldata$genotype == geno & alldata$rep == rep,]$y))
  }
  ally = do.call(rbind, ally)
  if(geno == 1) {
    res = array(ally, dim = c(nrep, length(time), 1))
  } else {
    res = array(c(res, ally), dim = c(nrep, length(time), dim(res)[3] + 1))
  }
}
dim(res) # should be n (rows) x nrT (columns) x ngeno (arrays)
```

### Setting up JAGS code
$$
y_{i,j} \sim MVN \bigg(\frac{d_i}{1 + exp(b_i(T - e_i))}, sd\cdot I\bigg)\\
sd \sim \text{Unif}(0, 100)\\
[b_i, d_i, e_i] \sim MVN(\vec\mu , \ \Sigma) \\
\text{prior for } \tau\ (\Sigma^{-1}) \sim \text{Wishart }\bigg(R =\begin{bmatrix}
    100 & & \\
    & 100 & \\
    & & 100
  \end{bmatrix}, \text{df} = 4\bigg)\\
z_{i,j} \sim N(0,1) \text{ for j} \in (b, d, e) \text{ and i} \in {1 ...\text{nRep}}\\
\text{GRM } = CC^T\\
\vec{b} = C\vec{z_b} + \mu_b \sim N(\mu_b, \text{GRM})\\
\vec{d} = C\vec{z_d} + \mu_d \sim N(\mu_d, \text{GRM})\\
\vec{e} = C\vec{z_e} + \mu_e \sim N(\mu_e, \text{GRM})\\
\mu_j \sim N(0, 100) \text{ for j} \in (b, d, e)
$$

```{r JAGS}
C = t(chol(GRM))
jagsData <- list("Y"=res,"N"=ngeno,"nrT"=nrT,"time"=time, "nRep" = nrep, "C" = C)

model_string <- "model {
  # dimensions of Y matrix = nRep x nrT x N
  for (i in 1:N) { # loop over genotypes
    for (t in 1:nrT) { # loop over time points
      for (j in 1:nRep) {
        Y[j, t, i] ~ dnorm(d[i] / (1 + exp(b[i] * (time[t] - e[i]))), 1/pow(sd,2)) 
      }
    }
  }
  sd ~ dunif(0, 100)
  
  for (i in 1:N) { z_b[i] ~ dnorm(0,1) }
  b[1:N] <- (C[,] %*% z_b[1:N]) + mu_b
  for (i in 1:N) { z_d[i] ~ dnorm(0,1) }
  d[1:N] <- (C[,] %*% z_d[1:N]) + mu_d
  for (i in 1:N) { z_e[i] ~ dnorm(0,1) }
  e[1:N] <- (C[,] %*% z_e[1:N]) + mu_e
  
  mu_b ~ dnorm(0, 0.01)
  mu_d ~ dnorm(0, 0.01)
  mu_e ~ dnorm(0, 0.01)
}"
```

### Running JAGS
```{r run}
# nadapt = 100000
# nupdate = 100000
# nimplement = 50000
nadapt = 10000
nupdate = 10000
nimplement = 5000

parameters = c("b", "d", "e", "sd", "mu_b", "mu_d", "mu_e")
model <- jags.model(textConnection(model_string),
                    data=jagsData, n.chains=1, n.adapt = nadapt, inits = list(.RNG.name = "base::Wichmann-Hill",.RNG.seed = seed))

update(model, n.iter=nupdate)
samples <- coda.samples(model, variable.names=parameters, n.iter=nimplement)
s = as.data.frame(as.matrix(samples))
head(s[,1:5])
```

## Plotting estimates

### Plotting b,d,e estimates
```{r plot param estimates, echo = FALSE}
total = dim(s)[1]; thin = rep(total/1000, 3)
print(paste("thinning to use every", total/1000))
p = c("b", "d", "e")
print(ngeno)
for (i in 1:length(p)) {
  index = grep(paste0(p[i],"\\["), colnames(s))
  subset = as.data.frame(s[,index])

  keep = seq(1, total,thin[i])
  subset = as.data.frame(subset[keep,])
  # print(dim(subset))
  subset = as.data.frame(rowMeans(subset))

  # print(dim(subset))
  colnames(subset) = c("mean")
  subset$iteration = 1:(total/thin[i])
  subset$param = p[i]
  if(i == 1) {
    graphdata = subset
  }
  else {
    graphdata = rbind(graphdata, subset)
  }
}
graphdata$iteration = as.numeric(graphdata$iteration)

ggplot(graphdata) +
  geom_histogram(aes(mean), bins = 20,fill="lightblue", colour="black") +
  facet_wrap(~param, scales = "free") +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))

ggplot(graphdata) +
  geom_point(aes(iteration, mean)) +
  facet_wrap(~param, scales = "free", nrow = 3) +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))
```
### Plotting sd estimates
```{r plot sd estimates, echo = FALSE}
total = dim(s)[1]; thin = total/1000
print(paste("thinning to use every", total/1000))
sd = as.data.frame(s$sd)
keep = seq(1, total,thin)
sd = as.data.frame(sd[keep, 1])
colnames(sd) = "sd"
sd$iteration = row.names(sd)
sd$iteration = as.numeric(sd$iteration)
ggplot(sd) +
  geom_point(aes(iteration, sd)) +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))
ggplot(sd) +
  geom_histogram(aes(sd), bins = 20,fill="lightblue", colour="black") +
  ggtitle(paste("Adapt =", nadapt, "Update =", nupdate, "Run =", nimplement))
```
